// Generated by build script, do not edit!
// This file is generated for the sole purpose of being included in Windows resource (.rc) files.
// DO NOT INCLUDE THIS FILE IN C++ CODE. Use #include "Runtime/Utilities/UnityConfiguration.h" instead.
#define UNITY_VERSION_BLD 5582853
#define UNITY_VERSION_UNDER_HASH "6000.2.1f1_55300504c302"
#define UNITY_VERSION_PARENS_HASH "6000.2.1f1 (55300504c302)"
#define UNITY_VERSION_WIN "6000.2.1.5582853"
